# Generated by Django 5.0.4 on 2024-04-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NginxLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(max_length=15)),
                ("date", models.DateTimeField()),
                ("http_method", models.CharField(max_length=10)),
                ("request_uri", models.TextField()),
                ("response_code", models.IntegerField()),
                ("response_size", models.IntegerField()),
            ],
        ),
    ]
