# Generated by Django 5.0.4 on 2024-04-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_processor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nginxlogentry",
            name="date",
            field=models.DateTimeField(default="22/Apr/2024:11:54:14", null=True),
        ),
        migrations.AlterField(
            model_name="nginxlogentry",
            name="http_method",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="nginxlogentry",
            name="ip_address",
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name="nginxlogentry",
            name="request_uri",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="nginxlogentry",
            name="response_code",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="nginxlogentry",
            name="response_size",
            field=models.IntegerField(null=True),
        ),
    ]
