# Generated by Django 5.0.4 on 2024-04-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_processor", "0002_alter_nginxlogentry_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nginxlogentry",
            name="date",
            field=models.DateTimeField(default="22/Apr/2024:11:54:37", null=True),
        ),
    ]
